---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ehb-media-pvc
  spec:
    resources:
      requests:
        storage: 1Gi
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce